### PR TITLE
[IMPL] Animation Easings

### PR DESCRIPTION
**Pull request by surge541**

### CODE REVIEW

**Comment by master7720** [comment]
i use arch btw

**Comment by Wolfsurge** [comment]
> i use arch btw

ok and?

**Comment by master7720** [comment]
> > i use arch btw
> 
> ok and?

i use arch btw and i respect wolfsurge

**Comment by Wolfsurge** [comment]
> > > i use arch btw
> > 
> > ok and?
> 
> i use arch btw and i respect wolfsurge

awesome

**Pull request merged**
