### PR TITLE
[IMPL] New GUI

### PR DESCRIPTION
**Pull request by pleasegivesource**
This pr is so messed up.

It's not perfect, but linus said it's time for pr.

[](https://011010010110110001111001.lol/3Ik90x4i)

Stuff that still needs to be added:
- Changelog window
- Icons
- Maybe some animations for minimizing/closing/opening windows?

### CODE REVIEW

**Comment by IUDevman** [comment]
Oh man

**Comment by master7720** [comment]
the window gui is just fine.

**Comment by Wolfsurge** [comment]
> the window gui is just fine.

yeah, it's 'fine', but like Linus said in the xeno server, it was a placeholder. this GUI is much better.

**Comment by master7720** [comment]
in school rn can you send me a pic?

**Comment by Wolfsurge** [comment]
image

**Comment by master7720** [comment]
SHEEEESH

**Comment by master7720** [comment]
thanks for the photo btw

**Comment by Wolfsurge** [comment]
> thanks for the photo btw

np.

**Pull request merged**
