### PR TITLE
[IMPL] Chams shader mode

### PR DESCRIPTION
**Pull request by DondaEnjoyerr**
added shader mode for chams. 
- Cosmos shader
- Smoke shader
- Lights shader

I plan to implement more shaders in the future

### CODE REVIEW

**Comment by unfidelity** [comment]
hi

**Comment by Sxmurai** [comment]
hi @unfidelity

**Comment by linustouchtips** [comment]
Shader Chams look good, however you broke normal chams

**Comment by Gopro336** [comment]
oh, ok, i'll take a look in a bit

**Comment by linustouchtips** [comment]
can u move these into shaders into esp actually

**Comment by master7720** [comment]
breh

**Comment by master7720** [comment]
JUST ADD IT LINUS

**Pull request closed without merging**
