### PR TITLE
[IMPL] Outline Fill shader + Dotted shader fix

### PR DESCRIPTION
**Pull request by Wolfsurge**

### CODE REVIEW

**Comment by master7720** [comment]
ay wold can you also fix the build issue too

**Comment by Wolfsurge** [comment]
I believe the build issue is because Linus is rewriting the CA, so where the CA is referenced (i.e. PresenceManager), it is using a variable from the rewrite, however Linus hasn't committed the rewrite so it causes the build to fail. Basically, no, but it will be fixed when Linus commits the new CA. However if you load Cosmos in an ide (e.g. IntelliJ) you can fix it by just changing the line(s) where it references the new CA, then build it.

**Comment by master7720** [comment]
> I believe the build issue is because Linus is rewriting the CA, so where the CA is referenced (i.e. PresenceManager), it is using a variable from the rewrite, however Linus hasn't committed the rewrite so it causes the build to fail. Basically, no, but it will be fixed when Linus commits the new CA. However if you load Cosmos in an ide (e.g. IntelliJ) you can fix it by just changing the line(s) where it references the new CA, then build it.

ok thanks babe

**Comment by master7720** [comment]
wait why are you making issues? arnt you a dev for this client you should get access to the repo

**Comment by Wolfsurge** [comment]
> wait why are you making issues? arnt you a dev for this client you should get access to the repo

idk I don't really know whether to call myself a dev lmao

**Comment by master7720** [comment]
> > wait why are you making issues? arnt you a dev for this client you should get access to the repo
> 
> idk I don't really know whether to call myself a dev lmao

you kinda did alot so idk

**Comment by Wolfsurge** [comment]
> > > wait why are you making issues? arnt you a dev for this client you should get access to the repo
> > 
> > idk I don't really know whether to call myself a dev lmao
> 
> you kinda did alot so idk

ig but there's also them needing to make sure my code style is correct as well as documented properly

**Comment by master7720** [comment]
btw can you add the tab gui

**Comment by master7720** [comment]
do it like what konas does you have the normal gui module then the TabGUI module

**Comment by Wolfsurge** [comment]
> btw can you add the tab gui 

@linustouchtips should I?

**Comment by master7720** [comment]
> > btw can you add the tab gui
> 
> @linustouchtips should I?

its a good idea tbh

**Comment by master7720** [comment]
you should make it so you can change from the old tab gui to the new tab gui

**Comment by Wolfsurge** [comment]
> > > btw can you add the tab gui
> > 
> > @linustouchtips should I?
> 
> its a good idea tbh

Yeah I mean it's not hard, just want to make sure the Linus is ok with it first :P

**Comment by master7720** [comment]
> > > > btw can you add the tab gui
> > > 
> > > 
> > > @linustouchtips should I?
> > 
> > 
> > its a good idea tbh
> 
> Yeah I mean it's not hard, just want to make sure the Linus is ok with it first :P

he will probably be ok with idk why he will not be ok with it

**Comment by master7720** [comment]
btw wolf if you have time could you rewrite the ViewModel

**Comment by Wolfsurge** [comment]
yeah maybe current viewmodel is kinda shit (sorry aesthetical)

**Comment by Wolfsurge** [comment]
tabgui has been approved @master7720

**Comment by Sxmurai** [comment]
> yeah maybe current viewmodel is kinda shit (sorry aesthetical)

i just havent fixed it yet

**Comment by Sxmurai** [comment]
i know whats wrong with it, ive just havent touched it in awhile

**Comment by master7720** [comment]
> tabgui has been approved @master7720

YES thank you

**Pull request merged**
