### PR TITLE
[IMPL] Jesus Module

### PR DESCRIPTION
**Pull request by Wolfsurge**
used wrong acc when committing :P

### CODE REVIEW

**Comment by linustouchtips** [comment]
This doesn't work on NCP Updated

**Comment by Wolfsurge** [comment]
ok, I might try to find a way round it (if I can be bothered)

**Comment by linustouchtips** [comment]
I will fix it

**Comment by Doogie13** [comment]
Having a non-ncp jesus isnt a bad thing

**Comment by Wolfsurge** [comment]
> Having a non-ncp jesus isnt a bad thing
> 

yea just add it as a mode

**Comment by linustouchtips** [comment]
> Having a non-ncp jesus isnt a bad thing

Yes it is, cause it won't work on 2b2t. I fixed up this entire pr regardless and added it.

**Pull request merged**
